package com.example.quizd

import android.content.Intent
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.os.Bundle
import android.os.CountDownTimer
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.constraintlayout.widget.ConstraintLayout
import kotlin.random.Random


var countDown = true//A boolean to keep track of whether or not the player can give an answer at this moment
val speed = 2.0f //How fast the player needs to move the phone for there to be input registered
val timeDelay: Long = 1000 //Won't allow players to reenter in data for this long (in Milliseconds)
var totalPoints = 0

class TermActivity : AppCompatActivity(), SensorEventListener {

        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            setContentView(R.layout.term_screen)

            val timer: Long = intent.getLongExtra("Timer", 31000) //how long the game will last
            var time_holder = timer/1000 //This is a variable that converts the time from miliseconds to whole seconds (mostly for the Textview)
            var timer_string = time_holder.toString() //Changes the Time Value into a string for It's associated text box to use

            setTerm()
            val timer_box: TextView = findViewById<TextView>(R.id.timer)
            object: CountDownTimer(31000, 1000){//Delays for timeDelay (in milliseconds)
            override fun onTick(millisUtilFinished: Long){
                time_holder -= 1
                timer_string = time_holder.toString()
                timer_box.text = timer_string
            }
                override fun onFinish() { //resets countdown so that a new answer can be received
                    val point_screen = Intent(this@TermActivity, PointScreen::class.java)
                    point_screen.putExtra("totalPoints", totalPoints)
                    startActivity(point_screen)
                    finish()
                }
            }.start() //starts the timer

            val sensorManager = getSystemService(SENSOR_SERVICE) as SensorManager//This and three lines down setup the gyroscope
            sensorManager.getDefaultSensor(Sensor.TYPE_GYROSCOPE)?.also { accelerometer ->
                sensorManager.registerListener(this, accelerometer, SensorManager.SENSOR_DELAY_NORMAL, SensorManager.SENSOR_DELAY_UI)
            }
        }

        var countDown = true//A boolean to keep track of whether or not the player can give an answer at this moment
        val speed = 4.0f //How fast the player needs to move the phone for there to be input registered
        val timeDelay: Long = 3000 //Won't allow players to reenter in data for this long (in Milliseconds)

        override fun onSensorChanged(p0: SensorEvent?) { //whenever the phone moves
            if (p0 != null && countDown) { //if the phone actually has moved
                if (p0.values[1] >= speed) { //if the movement is greater than our speed
                    on_correct_answer(timeDelay) // What To do on a correct Answer
                    countDown = false //Disables any other answers
                    object: CountDownTimer(timeDelay, 1000){//Delays for timeDelay (in milliseconds)
                    override fun onTick(millisUtilFinished: Long){

                    }
                        override fun onFinish() { //resets countdown so that a new answer can be received
                            countDown = true
                        }
                    }.start() //starts the timer
                }else if(p0.values[1] <= -speed) { //Flip down
                    on_incorrect_answer(timeDelay) //What to do on a flip-down event
                    countDown = false
                    object: CountDownTimer(timeDelay, 1000){
                        override fun onTick(millisUtilFinished: Long){

                        }
                        override fun onFinish() {
                            countDown = true
                        }
                    }.start()
                }
            }
        }

        fun on_correct_answer(timeDelay: Long) {
            totalPoints += 1
            val newDelay = timeDelay/2 //The time the screen will be green, MUST BE LOWER THAN TIME DELAY
            val myConstraint = findViewById<ConstraintLayout>(R.id.Constraint)
            myConstraint.setBackgroundResource(R.color.correct_green)
            val textView: TextView = findViewById<TextView>(R.id.animal_term)
            textView.text = "Correct"
            object: CountDownTimer(newDelay, 3000){//Delays for timeDelay (in milliseconds)
            override fun onTick(millisUtilFinished: Long){

            }
                override fun onFinish() { //resets countdown so that a new answer can be received
                    reset_background()
                }
            }.start() //starts the timer
            //ADD POINTS
        }

    fun on_incorrect_answer(timeDelay: Long) {
        val newDelay = timeDelay/2 //The time the screen will be red, MUST BE LESS THAN TIMEDELAY
        val myConstraint = findViewById<ConstraintLayout>(R.id.Constraint)
        myConstraint.setBackgroundResource(R.color.incorrect_red)
        val textView: TextView = findViewById<TextView>(R.id.animal_term)
        textView.text = "Incorrect"
        object: CountDownTimer(newDelay, 3000){//Delays for timeDelay (in milliseconds)
        override fun onTick(millisUtilFinished: Long){

        }
            override fun onFinish() { //resets countdown so that a new answer can be received
                reset_background()
            }
        }.start() //starts the timer
    }

    fun reset_background() {
        val myConstraint = findViewById<ConstraintLayout>(R.id.Constraint)
        myConstraint.setBackgroundResource(R.color.quizd_blue)
        setTerm()
    }
        fun termSelect(): String {
            val number = intent.getIntExtra("choice", 1) //Gets a number depending on category screen button pressed
            var terms = setOf("hello")
            if(number == 1) { //Checks to see if the number is 1 (associated with animals
                terms = setOf("Aardvark",
                        "Aardwolf",
                        "African Elephant",
                        "African Tree Pangolin",
                        "Alligator",
                        "Alpaca",
                        "Anteater",
                        "Antelope",
                        "Ape(s)",
                        "Arabian Horse",
                        "Armadillo",
                        "Arthropod(s)",
                        "Asian Elephant",
                        "Aye-Aye",
                        "Baboon",
                        "Badger",
                        "Bandicoot",
                        "Bat(s)",
                        "Bearded Dragon",
                        "Beaver",
                        "Beluga Whale",
                        "Bengal Tiger",
                        "Big-Horned Sheep",
                        "Billy Goat",
                        "Bird(s)",
                        "Bison",
                        "Black Bear",
                        "Black Footed Rhino",
                        "Black Howler Monkey",
                        "Black Rhino",
                        "Blacktip Reef Shark",
                        "Blue Shark",
                        "Blue Whale",
                        "Boar",
                        "Bob-Cat",
                        "Bonobo",
                        "Bottlenose Dolphin",
                        "Bottlenose Whale",
                        "Brown Bear",
                        "Buffalo",
                        "Bull",
                        "Bull frog",
                        "Caiman Lizard",
                        "Camel",
                        "Capuchin Monkey",
                        "Capybara",
                        "Caribou",
                        "Cat(s)",
                        "Cattle",
                        "Cheetah",
                        "Chimpanzee",
                        "Chinchilla",
                        "Chipmunk",
                        "Common Dolphin",
                        "Common Seal",
                        "Coral(s) and Anemone(s)",
                        "Cougar",
                        "Cow(s)",
                        "Coyote",
                        "Crocodile",
                        "Crustacean(s)",
                        "Dart Frog",
                        "Deer",
                        "Degus",
                        "Dik-Dik",
                        "Dingo",
                        "Dog(s)",
                        "Dogfish Shark",
                        "Dolphin",
                        "Donkey",
                        "Door Mouse",
                        "Dormouse",
                        "Draft Horse",
                        "Duckbill Platypus",
                        "Dugong",
                        "Dusky Shark",
                        "Elephant",
                        "Elephant Seal",
                        "Elk",
                        "Ermine",
                        "Eurasian Lynx",
                        "Ferret",
                        "Fish(es)",
                        "Florida Panther",
                        "Flying Fox",
                        "Fox",
                        "Fresh Water Crocodile",
                        "Frog",
                        "Fur Seal",
                        "Galapagos Land Iguana",
                        "Galapagos Shark",
                        "Galapagos Tortoise",
                        "Gazelle",
                        "Gecko",
                        "Giant Anteater",
                        "Giant Panda",
                        "Gibbon",
                        "Giraffe",
                        "Goat",
                        "Gopher",
                        "Gorilla",
                        "Gray Fox",
                        "Gray Nurse Shark",
                        "Gray Reef Shark",
                        "Gray Whale",
                        "Great White Shark",
                        "Green Poison Dart Frog",
                        "Green Sea Turtle",
                        "Grizzly Bear",
                        "Groundhog",
                        "Guinea Pig",
                        "Hairy-Nosed Wombat",
                        "Hammerhead Shark",
                        "Harbor Porpoise",
                        "Harbor Seal",
                        "Hare",
                        "Harp Seal",
                        "Hawaiian Monk Seal",
                        "Hedgehog",
                        "Hippopotamus",
                        "Horn Shark",
                        "Horse(s)",
                        "Howler Monkey",
                        "Humpback Whale",
                        "Hyena",
                        "Hyrax",
                        "Iguana",
                        "Iguanodon",
                        "Impala",
                        "Insect(s)",
                        "Irrawaddy Dolphin",
                        "Jackal",
                        "Jackrabbit",
                        "Jaguar",
                        "Jellyfish",
                        "Kangaroo",
                        "Kermode Bear",
                        "Killer Whale",
                        "Koala",
                        "Komodo Dragon",
                        "Kookaburra",
                        "Lama",
                        "Lamb",
                        "Lancelet",
                        "Least Weasel",
                        "Leatherback Sea Turtle",
                        "Lemming",
                        "Lemon Shark",
                        "Lemur",
                        "Leopard",
                        "Leopard Gecko",
                        "Leopard Seal",
                        "Leopard Shark",
                        "Lion",
                        "Llama",
                        "Loggerhead Turtles",
                        "Lynx",
                        "Mako Shark",
                        "Manatee",
                        "Manta Ray",
                        "Mantis",
                        "Marbled Salamander",
                        "Marmot",
                        "Marsupial(s)",
                        "Meerkat",
                        "Megamouth Shark",
                        "Melon-Headed Whale",
                        "Miniature Donkey",
                        "Mink",
                        "Minke Whale",
                        "Mole",
                        "Mole Salamander",
                        "Mollusk(s)",
                        "Mongoose",
                        "Monitor Lizard",
                        "Monk Seal",
                        "Monkey",
                        "Moose",
                        "Mountain Lion",
                        "Mouse",
                        "Mule",
                        "Muskox",
                        "Muskrat",
                        "Naked Mole Rat",
                        "Narwhal",
                        "Nautilus",
                        "Newt",
                        "Northern Right Whale",
                        "Nurse Shark",
                        "Nutria",
                        "Nyala",
                        "Ocelot",
                        "Octopus",
                        "Okapi",
                        "Opossum",
                        "Orangutan",
                        "Orca",
                        "Otter",
                        "Ox",
                        "Panda",
                        "Panther",
                        "Pig",
                        "Pilot Whale",
                        "Pine Marten",
                        "Platypus",
                        "Polar Bear",
                        "Porcupine",
                        "Porpoise",
                        "Possum",
                        "Potbellied Pig",
                        "Potto",
                        "Prairie Dog",
                        "Proboscis Monkey",
                        "Przewalski's Wild horse" ,
                        "Puma",
                        "Pygmy Hippopotamus",
                        "Pygmy Right Whale",
                        "Pygmy Sperm Whale",
                        "Quokkas",
                        "Quolls",
                        "Rabbit",
                        "Raccoon",
                        "Rat",
                        "Ray",
                        "Red Fox",
                        "Red Kangaroo",
                        "Red Panda",
                        "Red-Eyed Tree Frog",
                        "Reef Shark",
                        "Reindeer",
                        "Rhino",
                        "Rhinoceros",
                        "Right Whale",
                        "Ringed Seal",
                        "Risso's Dolphin" ,
                        "River Dolphin",
                        "Salamander",
                        "Sandbar Shark",
                        "Scalloped Hammerhead Shark",
                        "Sea Lion",
                        "Sea Turtles",
                        "Seal",
                        "Sei Whale",
                        "Shark",
                        "Sheep",
                        "Shortfin Mako Shark",
                        "Siberian Tiger",
                        "Silky Shark",
                        "Skink",
                        "Skunk",
                        "Slender Loris",
                        "Sloth",
                        "Sloth Bear",
                        "Snake(s)",
                        "Snow Fox",
                        "Snow Hare",
                        "Snow Leopard",
                        "Snow Monkey",
                        "Somali Wild Ass",
                        "Spectacled Bear",
                        "Sperm Whale",
                        "Spider Monkey",
                        "Spiny Dogfish Shark",
                        "Spotted Dolphin",
                        "Squirrel",
                        "Star-Nosed Mole",
                        "Stellar Sea Lion",
                        "Striped Dolphin",
                        "Sun Bear",
                        "Takin",
                        "Tamarin",
                        "Tapir",
                        "Tasmanian Devil",
                        "Tasmanian Tiger",
                        "Terrapin",
                        "Thresher Shark",
                        "Tiger",
                        "Tiger Salamander",
                        "Tiger Shark",
                        "Topi",
                        "Tortoise",
                        "Tree Frog",
                        "Turtle",
                        "Uakari",
                        "Vampire Bat",
                        "Vancouver Island Marmot",
                        "Vervet Monkey",
                        "Vicuna",
                        "Vole",
                        "Wallaby",
                        "Walrus",
                        "Warthog",
                        "Water Buffalo",
                        "Weasel",
                        "Whale Shark",
                        "Whale(s)",
                        "White Rhino",
                        "White Tailed Deer",
                        "White-Beaked Dolphin",
                        "Whitetip Reef Shark",
                        "Wildcat",
                        "Wildebeest",
                        "Wobbegong Shark",
                        "Wolf",
                        "Wolverine",
                        "Wombat",
                        "Woodchuck",
                        "Yak",
                        "Yellow-Bellied Marmot",
                        "Zebra",
                        "Zebu",
                        "Zorilla",)
            }
            else if(number == 2)
            {
                terms = setOf("Afghanistan",
                    "Albania",
                    "Algeria",
                    "Andorra",
                    "Angola",
                    "Antigua and Barbuda",
                    "Argentina",
                    "Armenia",
                    "Australia",
                    "Austria",
                    "Azerbaijan",
                    "Bahamas",
                    "Bahrain",
                    "Bangladesh",
                    "Barbados",
                    "Belarus",
                    "Belgium",
                    "Belize",
                    "Benin",
                    "Bhutan",
                    "Bolivia",
                    "Bosnia and Herzegovina",
                    "Botswana",
                    "Brazil",
                    "Brunei",
                    "Bulgaria",
                    "Burkina Faso",
                    "Burundi",
                    "Cabo Verde",
                    "Cambodia",
                    "Cameroon",
                    "Canada",
                    "Central African Republic (CAR)",
                    "Chad",
                    "Chile",
                    "China",
                    "Colombia",
                    "Comoros",
                    "Democratic Republic of the Congo",
                    "Republic of the Congo",
                    "Costa Rica",
                    "Cote d'Ivoire",
                    "Croatia",
                    "Cuba",
                    "Cyprus",
                    "Czechia",
                    "Denmark",
                    "Djibouti",
                    "Dominica",
                    "Dominican Republic",
                    "Ecuador",
                    "Egypt",
                    "El Salvador",
                    "Equatorial Guinea",
                    "Eritrea",
                    "Estonia",
                    "Eswatini",
                    "Ethiopia",
                    "Fiji",
                    "Finland",
                    "France",
                    "Gabon",
                    "Gambia",
                    "Georgia",
                    "Germany",
                    "Ghana",
                    "Greece",
                    "Grenada",
                    "Guatemala",
                    "Guinea",
                    "Guinea-Bissau",
                    "Guyana",
                    "Haiti",
                    "Honduras",
                    "Hungary",
                    "Iceland",
                    "India",
                    "Indonesia",
                    "Iran",
                    "Iraq",
                    "Ireland",
                    "Israel",
                    "Italy",
                    "Jamaica",
                    "Japan",
                    "Jordan",
                    "Kazakhstan",
                    "Kenya",
                    "Kiribati",
                    "Kosovo",
                    "Kuwait",
                    "Kyrgyzstan",
                    "Laos",
                    "Latvia",
                    "Lebanon",
                    "Lesotho",
                    "Liberia",
                    "Libya",
                    "Liechtenstein",
                    "Lithuania",
                    "Luxembourg",
                    "Madagascar",
                    "Malawi",
                    "Malaysia",
                    "Maldives",
                    "Mali",
                    "Malta",
                    "Marshall Islands",
                    "Mauritania",
                    "Mauritius",
                    "Mexico",
                    "Micronesia",
                    "Moldova",
                    "Monaco",
                    "Mongolia",
                    "Montenegro",
                    "Morocco",
                    "Mozambique",
                    "Myanmar",
                    "Namibia",
                    "Nauru",
                    "Nepal",
                    "Netherlands",
                    "New Zealand",
                    "Nicaragua",
                    "Niger",
                    "Nigeria",
                    "North Korea",
                    "North Macedonia",
                    "Norway",
                    "Oman",
                    "Pakistan",
                    "Palau",
                    "Palestine",
                    "Panama",
                    "Papua New Guinea",
                    "Paraguay",
                    "Peru",
                    "Philippines",
                    "Poland",
                    "Portugal",
                    "Qatar",
                    "Romania",
                    "Russia",
                    "Rwanda",
                    "Saint Kitts and Nevis",
                    "Saint Lucia",
                    "Saint Vincent and the Grenadines",
                    "Samoa",
                    "San Marino",
                    "Sao Tome and Principe",
                    "Saudi Arabia",
                    "Senegal",
                    "Serbia",
                    "Seychelles",
                    "Sierra Leone",
                    "Singapore",
                    "Slovakia",
                    "Slovenia",
                    "Solomon Islands",
                    "Somalia",
                    "South Africa",
                    "South Korea",
                    "South Sudan",
                    "Spain",
                    "Sri Lanka",
                    "Sudan",
                    "Suriname",
                    "Sweden",
                    "Switzerland",
                    "Syria",
                    "Taiwan",
                    "Tajikistan",
                    "Tanzania",
                    "Thailand",
                    "Timor-Leste",
                    "Togo",
                    "Tonga",
                    "Trinidad and Tobago",
                    "Tunisia",
                    "Turkey",
                    "Turkmenistan",
                    "Tuvalu",
                    "Uganda",
                    "Ukraine",
                    "United Arab Emirates (UAE)",
                    "United Kingdom (UK)",
                    "United States of America (USA)",
                    "Uruguay",
                    "Uzbekistan",
                    "Vanuatu",
                    "Vatican City (Holy See)",
                    "Venezuela",
                    "Vietnam",
                    "Yemen",
                    "Zambia",
                    "Zimbabwe",
                    "Alabama",
                    "Alaska",
                    "Arizona",
                    "Arkansas",
                    "California",
                    "Colorado",
                    "Connecticut",
                    "Delaware",
                    "Florida",
                    "Georgia",
                    "Hawaii",
                    "Idaho",
                    "Illinois",
                    "Indiana",
                    "Iowa",
                    "Kansas",
                    "Kentucky",
                    "Louisiana",
                    "Maine",
                    "Maryland",
                    "Massachusetts",
                    "Michigan",
                    "Minnesota",
                    "Mississippi",
                    "Missouri",
                    "Montana",
                    "Nebraska",
                    "Nevada",
                    "New Hampshire",
                    "New Jersey",
                    "New Mexico",
                    "New York",
                    "North Carolina",
                    "North Dakota",
                    "Ohio",
                    "Oklahoma",
                    "Oregon",
                    "Pennsylvania",
                    "Rhode Island",
                    "South Carolina",
                    "South Dakota",
                    "Tennessee",
                    "Texas",
                    "Utah",
                    "Vermont",
                    "Virginia",
                    "Washington",
                    "West Virginia",
                    "Wisconsin",
                    "Wyoming")

            }
            else if(number == 3)
            {
                terms = setOf("Jesus",
                    "Adolf Hitler",
                    "Marilyn Monroe",
                    "Donald Trump",
                    "Mao",
                    "Albert Enstein",
                    "Cleopatra",
                    "Michael Jackson",
                    "Charlie Chaplin",
                    "Abraham Lincoln",
                    "Julius Ceasar",
                    "Joan of Arc",
                    "John Lennon",
                    "Mother Theresa",
                    "John F. Kennedy",
                    "Gandhi",
                    "Nelson Mandela",
                    "Princess Diana",
                    "Leonardo Da Vinci",
                    "Christopher Columbus",
                    "Queen Victoria",
                    "Pablo Picasso",
                    "Socrates",
                    "J.K. Rowling",
                    "Audrey Hepburn",
                    "Steven Spielberg",
                    "George Washington",
                    "Frida Kahlo",
                    "Winston Churchill",
                    "Madonna",
                    "Augustus",
                    "Van Gogh",
                    "Leonardo DiCaprio",
                    "Jane Austen",
                    "Paul McCartney",
                    "William Shakespeare",
                    "Johnny Depp",
                    "Joseph Stalin",
                    "Tutankhamen",
                    "Charles Dickens",
                    "Vladimir Putin",
                    "Plato",
                    "Elvis Presley",
                    "Mark Twain",
                    "Barack Obama",
                    "Whitney Houston",
                    "Michelangelo",
                    "Tom Hanks",
                    "Ellen Degeneres",
                    "Claude Monet",
                    "Martin Luther",
                    "Rowan Atkinson",
                    "Bob Dylan",
                    "John Travolta",
                    "Marco Polo",
                    "Pocahontas",
                    "Tolkien",
                    "Alexander the Great",
                    "Vlad Dracula",
                    "Britney Spears",
                    "Alfred Nobel",
                    "Angelina Jolie",
                    "Andy Warhol",
                    "Prince",
                    "Homer",
                    "Cristiano Ronaldo",
                    "Che Guevara",
                    "Elizabeth Taylor",
                    "Martin Luther King",
                    "David Beckham",
                    "Vasco Da Gama",
                    "Queen Elizabeth II",
                    "Walt Disney",
                    "Kim Jong Il",
                    "Tiger Woods",
                    "Oprah Winfrey",
                    "Wolfgang Amadeus Mozart",
                    "Malcolm X",
                    "Quentin Tarantino",
                    "Lady Gaga",
                    "Theodore Roosevelt",
                    "Jackie Chan",
                    "Anne Frank",
                    "Louis Armstrong",
                    "David Bowie",
                    "George Clooney",
                    "William the Conqueror",
                    "Yoko Ono",
                    "Neil Armstrong",
                    "Ernest Hemingway",
                    "Queen Elizabeth I",
                    "Charles Darwin",
                    "Napoleon",
                    "Malala Yousafzai",
                    "Beyoncé",
                    "Alfred Hitchcock",
                    "Salvador Dali",
                    "Genghis Khan",
                    "Marie Antoinette",
                    "Rembrandt",
                    "Daniel Craig",
                    "Rasputin",
                    "Osama Bin Laden",
                    "Will Smith",
                    "Nero",
                    "Stephen Hawking",
                    "The Zodiac Killer",
                    "Agatha Christie",
                    "Marlon Brando",
                    "Edgar Allen Poe",
                    "Ai Weiwei",
                    "Mariah Carey",
                    "Johannes Gutenberg",
                    "Edvard Munch",
                    "Olivia Newton-John",
                    "Beethoven",
                    "Stevie Wonder",
                    "Clint Eastwood",
                    "Isaac Newton",
                    "Aretha Franklin",
                    "Elton John",
                    "Meryl Streep",
                    "Bach",
                    "Jim Morrison",
                    "Aristotele",
                    "Michael Jordan",
                    "Steve Jobs",
                    "Coco Chanel",
                    "Bill Clinton",
                    "Bono",
                    "Muhammad Ali",
                    "Bill Gates",
                    "Galileo Galilei",
                    "Marvin Gaye",
                    "Robert De Niro",
                    "Thomas Jefferson",
                    "Lionel Messi",
                    "Karl Marx",
                    "Taylor Swift",
                    "Alexander Graham Bell",
                    "Mark Zuckerberg",
                    "Confucius",
                    "Benjamin Franklin",
                    "Adele",
                    "Pythagoras",
                    "Lenin",
                    "Archimedes",
                    "Jennifer Lawrence",
                    "Al Pacino",
                    "Sigmund Freud",
                    "Johannes Kepler",
                    "Henri Matisse",
                    "Fidel Castro",
                    "Brad Pitt",
                    "Justin Bieber",
                    "George Orwell",
                    "Bob Marley",
                    "Immanuel Kant",
                    "Rosa Parks",
                    "Sitting Bull",
                    "Ronald Reagan",
                    "Rihanna",
                    "Frank Sinatra",
                    "Oscar Wilde",
                    "Justin Timberlake",
                    "Kafka",
                    "Hans Christian Andersen",
                    "James Dean",
                    "Bruce Lee",
                    "Celine Dion",
                    "James Cook",
                    "Kim Kardashian",
                    "Dolly Parton",
                    "George Bush",
                    "Chopin",
                    "Raphael",
                    "Margaret Thatcher",
                    "Shania Twain",
                    "Eminem",
                    "Leo Tolstoy",
                    "Edgar Degas",
                    "Sandro Botticelli",
                    "Hadrian",
                    "Frank Lloyd Wright",
                    "David Livingstone",
                    "Amelia Earhart",
                    "Grace Kelly",
                    "Bruce Springsteen",
                    "Tom Cruise",
                    "Shakira",
                    "Stephen King",
                    "Hillary Clinton",
                    "Marie Curie",
                    "Twiggy",
                    "Kate Winslet",
                    "Jay-Z",
                    "Edith Piaf",
                    "Dalai Lama",
                    "Clark Gable",
                    "Amy Winehouse")

            }
            else
            {
                terms = setOf("The Revenant (2015)",
                    "The Shawshank Redemption (1994)",
                    "The Godfather (1972)",
                    "The Dark Knight (2008)",
                    "The Godfather: Part II (1974)",
                    "12 Angry Men (1957)",
                    "Schindler's List (1993)",
                    "The Lord of the Rings: The Return of the King (2003)",
                    "Pulp Fiction (1994)",
                    "The Lord of the Rings: The Fellowship of the Ring (2001)",
                    "Forrest Gump (1994)",
                    "Fight Club (1999)",
                    "Inception (2010)",
                    "The Lord of the Rings: The Two Towers (2002)",
                    "Star Wars: Episode V - The Empire Strikes Back (1980)",
                    "The Matrix (1999)",
                    "Goodfellas (1990)",
                    "One Flew Over the Cuckoo's Nest (1975)",
                    "It's a Wonderful Life (1946)",
                    "Se7en (1995)",
                    "The Silence of the Lambs (1991)",
                    "Saving Private Ryan (1998)",
                    "Interstellar (2014)",
                    "The Green Mile (1999)",
                    "Star Wars (1977)",
                    "Terminator 2: Judgment Day (1991)",
                    "Back to the Future (1985)",
                    "The Pianist (2002)",
                    "Leon: The Professional (1994)",
                    "Psycho (1960)",
                    "The Lion King (1994)",
                    "Gladiator (2000)",
                    "American History X (1998)",
                    "The Usual Suspects (1995)",
                    "The Departed (2006)",
                    "The Prestige (2006)",
                    "Modern Times (1936)",
                    "Casablanca (1942)",
                    "Whiplash (2014)",
                    "Rear Window (1954)",
                    "Alien (1979)",
                    "Apocalypse Now (1979)",
                    "Memento (2000)",
                    "Indiana Jones and the Raiders of the Lost Ark (1981)",
                    "Django Unchained (2012)",
                    "Sunset Blvd. (1950)",
                    "WALL·E (2008)",
                    "The Great Dictator (1940)",
                    "Paths of Glory (1957)",
                    "Witness for the Prosecution (1957)",
                    "Avengers: Infinity War (2018)",
                    "Spider-Man: No Way Home (2021)",
                    "The Shining (1980)",
                    "The Dark Knight Rises (2012)",
                    "Aliens (1986)",
                    "Joker (2019)",
                    "Spider-Man: Into the Spider-Verse (2018)",
                    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)",
                    "American Beauty (1999)",
                    "Avengers: Endgame (2019)",
                    "Coco (2017)",
                    "Braveheart (1995)",
                    "Amadeus (1984)",
                    "Once Upon a Time in America (1984)",
                    "Toy Story (1995)",
                    "Inglourious Basterds (2009)",
                    "Hamilton (2020)",
                    "Singin' in the Rain (1952)",
                    "Good Will Hunting (1997)",
                    "Requiem for a Dream (2000)",
                    "Toy Story 3 (2010)",
                    "Star Wars: Episode VI - Return of the Jedi (1983)",
                    "Eternal Sunshine of the Spotless Mind (2004)",
                    "2001: A Space Odyssey (1968)",
                    "Lawrence of Arabia (1962)",
                    "Reservoir Dogs (1992)",
                    "Citizen Kane (1941)",
                    "North by Northwest (1959)",
                    "Double Indemnity (1944)",
                    "The Apartment (1960)",
                    "Vertigo (1958)",
                    "A Clockwork Orange (1971)",
                    "Scarface (1983)",
                    "To Kill a Mockingbird (1962)",
                    "The Sting (1973)",
                    "Full Metal Jacket (1987)",
                    "The Batman (2022)",
                    "Taxi Driver (1976)",
                    "Up (2009)",
                    "Heat (1995)",
                    "The Kid (1921)",
                    "Snatch (2000)",
                    "L.A. Confidential (1997)",
                    "Judgment at Nuremberg (1961)",
                    "Die Hard (1988)",
                    "Indiana Jones and the Last Crusade (1989)",
                    "1917 (2019)",
                    "The Father (2020)",
                    "Batman Begins (2005)",
                    "All About Eve (1950)",
                    "Some Like It Hot (1959)",
                    "Green Book (2018)",
                    "The Wolf of Wall Street (2013)",
                    "The Treasure of the Sierra Madre (1948)",
                    "Casino (1995)",
                    "Unforgiven (1992)",
                    "A Beautiful Mind (2001)",
                    "Monty Python and the Holy Grail (1975)",
                    "The Great Escape (1963)",
                    "There Will Be Blood (2007)",
                    "The Sixth Sense (1999)",
                    "Shutter Island (2010)",
                    "Gone with the Wind (1939)",
                    "The Truman Show (1998)",
                    "The Elephant Man (1980)",
                    "V for Vendetta (2005)",
                    "Jurassic Park (1993)",
                    "Raging Bull (1980)",
                    "Kill Bill: Vol. 1 (2003)",
                    "Finding Nemo (2003)",
                    "Chinatown (1974)",
                    "Dial M for Murder (1954)",
                    "No Country for Old Men (2007)",
                    "Lock, Stock and Two Smoking Barrels (1998)",
                    "Inside Out (2015)",
                    "The Bridge on the River Kwai (1957)",
                    "The Thing (1982)",
                    "Warrior (2011)",
                    "The Gold Rush (1925)",
                    "To Be or Not to Be (1942)",
                    "The General (1926)",
                    "Trainspotting (1996)",
                    "Three Billboards Outside Ebbing, Missouri (2017)",
                    "Gran Torino (2008)",
                    "On the Waterfront (1954)",
                    "Mr. Smith Goes to Washington (1939)",
                    "Klaus (2019)",
                    "Fargo (1996)",
                    "The Third Man (1949)",
                    "Harry Potter and the Deathly Hallows: Part 2 (2011)",
                    "Prisoners (2013)",
                    "Ben-Hur (1959)",
                    "The Best Years of Our Lives (1946)",
                    "In the Name of the Father (1993)",
                    "Million Dollar Baby (2004)",
                    "Barry Lyndon (1975)",
                    "Catch Me If You Can (2002)",
                    "Before Sunrise (1995)",
                    "The Deer Hunter (1978)",
                    "Mary and Max (2009)",
                    "12 Years a Slave (2013)",
                    "Hacksaw Ridge (2016)",
                    "Gone Girl (2014)",
                    "How to Train Your Dragon (2010)",
                    "Room (2015)",
                    "The Grand Budapest Hotel (2014)",
                    "The Big Lebowski (1998)",
                    "Mad Max: Fury Road (2015)",
                    "The Grapes of Wrath (1940)",
                    "Hotel Rwanda (2004)",
                    "Monsters, Inc. (2001)",
                    "Dead Poets Society (1989)",
                    "Jaws (1975)",
                    "Ford v Ferrari (2019)",
                    "Hachi: A Dog's Tale (2009)",
                    "Rocky (1976)",
                    "Network (1976)",
                    "Stand by Me (1986)",
                    "Platoon (1986)",
                    "The Red Shoes (1948)",
                    "Rush (2013)",
                    "Into the Wild (2007)",
                    "Rebecca (1940)",
                    "It Happened One Night (1934)",
                    "Logan (2017)",
                    "The Wizard of Oz (1939)",
                    "All Quiet on the Western Front (1930)",
                    "The Terminator (1984)",
                    "The Sound of Music (1965)",
                    "Cool Hand Luke (1967)",
                    "Before Sunset (2004)",
                    "Spotlight (2015)",
                    "The Exorcist (1973)",
                    "Inherit the Wind (1960)",
                    "Paper Moon (1973)",
                    "White Heat (1949)",
                    "Groundhog Day (1993)",
                    "Ratatouille (2007)",
                    "The Incredibles (2004)",
                    "Dune (2021)",
                    "The Man Who Shot Liberty Valance (1962)",
                    "Ace in the Hole (1951)",
                    "Gandhi (1982)",
                    "Pirates of the Caribbean: The Curse of the Black Pearl (2003)",
                    "Life of Brian (1979)",
                    "The Help (2011)",
                    "The Iron Giant (1999)",
                    "Beauty and the Beast (1991)",
                    "Aladdin (1992)",
                    "Dances with Wolves (1990)",
                    "Paris, Texas (1984)",
                    "Guardians of the Galaxy (2014)",
                    "Donnie Darko (2001)",
                    "Soul (2020)",
                    "Roman Holiday (1953)",
                    "Scent of a Woman (1992)",
                    "Dog Day Afternoon (1975)",
                    "Kill Bill: Vol. 2 (2004)",
                    "JFK (1991)",
                    "The Shop Around the Corner (1940)",
                    "Lion (2016)",
                    "The Avengers (2012)",
                    "Song of the Sea (2014)",
                    "Slumdog Millionaire (2008)",
                    "The Princess Bride (1987)",
                    "Butch Cassidy and the Sundance Kid (1969)",
                    "The Imitation Game (2014)",
                    "Rosemary's Baby (1968)",
                    "The Bourne Ultimatum (2007)",
                    "Anatomy of a Murder (1959)",
                    "Brief Encounter (1945)",
                    "Sin City (2005)",
                    "Magnolia (1999)",
                    "What Ever Happened to Baby Jane? (1962)",
                    "The King's Speech (2010)",
                    "Rain Man (1988)",
                    "Casino Royale (2006)",
                    "La La Land (2016)",
                    "The Message (1976)",
                    "Kind Hearts and Coronets (1949)",
                    "Zootopia (2016)",
                    "The Graduate (1967)",
                    "The Legend of 1900 (1998)",
                    "Black Swan (2010)",
                    "The Martian (2015)",
                    "Who's Afraid of Virginia Woolf? (1966)",
                    "The Pursuit of Happyness (2006)",
                    "12 Monkeys (1995)",
                    "Sweet Smell of Success (1957)",
                    "Blood Diamond (2006)",
                    "The Straight Story (1999)",
                    "Dogville (2003)",
                    "Planet of the Apes (1968)",
                    "Papillon (1973)",
                    "Secrets & Lies (1996)",
                    "The Night of the Hunter (1955)",
                    "Her (2013)",
                    "Cinderella Man (2005)",
                    "Annie Hall (1977)",
                    "Sling Blade (1996)")
            }
            var randomNum = Random.nextInt(0, terms.size)
            return terms.elementAt(randomNum)

        }
        fun setTerm()
        {
            val term = termSelect()
            val textView: TextView = findViewById<TextView>(R.id.animal_term)
            textView.text = term
        }

        override fun onAccuracyChanged(p0: Sensor?, p1: Int) { //This line is needed for some reason
        }
    }
